package citations

// BookIDs maps canonical book names to BYU Scripture Citation Index book IDs.
// These IDs were extracted from the navigation structure at https://scriptures.byu.edu/
var BookIDs = map[string]int{
	// Old Testament
	"Genesis":         101,
	"Exodus":          102,
	"Leviticus":       103,
	"Numbers":         104,
	"Deuteronomy":     105,
	"Joshua":          106,
	"Judges":          107,
	"Ruth":            108,
	"1 Samuel":        109,
	"2 Samuel":        110,
	"1 Kings":         111,
	"2 Kings":         112,
	"1 Chronicles":    113,
	"2 Chronicles":    114,
	"Ezra":            115,
	"Nehemiah":        116,
	"Esther":          117,
	"Job":             118,
	"Psalms":          119,
	"Proverbs":        120,
	"Ecclesiastes":    121,
	"Song of Solomon": 122,
	"Isaiah":          123,
	"Jeremiah":        124,
	"Lamentations":    125,
	"Ezekiel":         126,
	"Daniel":          127,
	"Hosea":           128,
	"Joel":            129,
	"Amos":            130,
	"Obadiah":         131,
	"Jonah":           132,
	"Micah":           133,
	"Nahum":           134,
	"Habakkuk":        135,
	"Zephaniah":       136,
	"Haggai":          137,
	"Zechariah":       138,
	"Malachi":         139,

	// New Testament
	"Matthew":         140,
	"Mark":            141,
	"Luke":            142,
	"John":            143,
	"Acts":            144,
	"Romans":          145,
	"1 Corinthians":   146,
	"2 Corinthians":   147,
	"Galatians":       148,
	"Ephesians":       149,
	"Philippians":     150,
	"Colossians":      151,
	"1 Thessalonians": 152,
	"2 Thessalonians": 153,
	"1 Timothy":       154,
	"2 Timothy":       155,
	"Titus":           156,
	"Philemon":        157,
	"Hebrews":         158,
	"James":           159,
	"1 Peter":         160,
	"2 Peter":         161,
	"1 John":          162,
	"2 John":          163,
	"3 John":          164,
	"Jude":            165,
	"Revelation":      166,

	// Book of Mormon
	"1 Nephi":         205,
	"2 Nephi":         206,
	"Jacob":           207,
	"Enos":            208,
	"Jarom":           209,
	"Omni":            210,
	"Words of Mormon": 211,
	"Mosiah":          212,
	"Alma":            213,
	"Helaman":         214,
	"3 Nephi":         215,
	"4 Nephi":         216,
	"Mormon":          217,
	"Ether":           218,
	"Moroni":          219,

	// Doctrine and Covenants
	"D&C":  302,
	"O.D.": 303,

	// Pearl of Great Price
	"Moses":             401,
	"Abraham":           402,
	"Facsimile":         403,
	"JS-M":              404,
	"JS-H":              405,
	"Articles of Faith": 406,
}

// sortedBookNames is ordered longest-first so prefix matching works correctly.
// e.g. "1 Corinthians" must match before "1 Chronicles".
// This also ensures "3 Nephi" matches before "Nephi".
var sortedBookNames = []string{
	// Longest names first
	"Song of Solomon",
	"Words of Mormon",
	"Articles of Faith",
	"2 Thessalonians",
	"1 Thessalonians",
	"2 Corinthians",
	"1 Corinthians",
	"2 Chronicles",
	"1 Chronicles",
	"Philippians",
	"Ecclesiastes",
	"Lamentations",
	"Deuteronomy",
	"Colossians",
	"Zephaniah",
	"Zechariah",
	"Habakkuk",
	"Ephesians",
	"Galatians",
	"Revelation",
	"2 Timothy",
	"1 Timothy",
	"Leviticus",
	"2 Samuel",
	"1 Samuel",
	"Jeremiah",
	"Nehemiah",
	"Philemon",
	"2 Nephi",
	"1 Nephi",
	"3 Nephi",
	"4 Nephi",
	"Proverbs",
	"Facsimile",
	"2 Kings",
	"1 Kings",
	"2 Peter",
	"1 Peter",
	"Hebrews",
	"Matthew",
	"Genesis",
	"Numbers",
	"2 John",
	"3 John",
	"1 John",
	"Abraham",
	"Helaman",
	"Obadiah",
	"Malachi",
	"Ezekiel",
	"Haggai",
	"Psalms",
	"Isaiah",
	"Daniel",
	"Mormon",
	"Romans",
	"Moroni",
	"Mosiah",
	"Exodus",
	"Joshua",
	"Judges",
	"Esther",
	"Hosea",
	"Micah",
	"Nahum",
	"Jonah",
	"Ether",
	"Jacob",
	"Moses",
	"James",
	"Jarom",
	"Titus",
	"Luke",
	"John",
	"Mark",
	"Joel",
	"Amos",
	"Acts",
	"Jude",
	"Alma",
	"Omni",
	"Enos",
	"Ezra",
	"Ruth",
	"D&C",
	"Job",
	"O.D.",
	"JS-M",
	"JS-H",
}
