<script setup lang="ts">
import { ref, computed } from 'vue'
import LinkedDefinition from '@/components/LinkedDefinition.vue'
import thummimData from '@/data/thummim-seed.json'

type Level = 'elementary' | 'eighth_grade' | 'college_plus'

interface LevelContent {
  headline: string
  body: string
  key_passages?: string[]
  conference_refs?: string[]
}

interface ThummimEntry {
  word: string
  levels: Record<Level, LevelContent>
  webster_1828_compare?: string
  substrate_study?: string
}

const entries = computed<ThummimEntry[]>(() => Object.values((thummimData as any).entries))
const selectedLevel = ref<Level>('eighth_grade')
const selectedWord = ref<string>(entries.value[0]?.word ?? '')

const current = computed<ThummimEntry | undefined>(() =>
  entries.value.find(e => e.word === selectedWord.value)
)

const LEVEL_LABELS: Record<Level, string> = {
  elementary: 'Elementary (age 7-11)',
  eighth_grade: '8th grade',
  college_plus: 'High school / college+',
}
</script>

<template>
  <div class="max-w-4xl mx-auto px-6 py-10">
    <header class="mb-8">
      <div class="inline-block px-3 py-1 bg-amber-100 border border-amber-300 text-amber-900 rounded-full text-xs font-medium mb-3">
        PREVIEW — 3 seed entries · proposal stage
      </div>
      <h1 class="text-3xl font-serif mb-2">Thummim 2026 Restoration Dictionary</h1>
      <p class="text-stone-600 leading-relaxed">
        A companion lens to Webster 1828: <strong>what does each word mean within the Restoration's own usage?</strong>
        Three grade-level renderings per entry — elementary, 8th grade, college+. Defined from scripture + General Conference, not secular dictionaries.
      </p>
      <p class="text-stone-500 text-sm mt-3">
        Proposal: <code class="bg-stone-100 px-1.5 py-0.5 rounded text-xs font-mono">.spec/proposals/thummim-restoration-dictionary.md</code>.
        These three seed entries demonstrate the shape; the full dictionary
        will be generated by a substrate pipeline (~150-200 doctrinal words).
      </p>
    </header>

    <!-- Word selector -->
    <div class="flex flex-wrap gap-2 mb-6">
      <button
        v-for="e in entries"
        :key="e.word"
        @click="selectedWord = e.word"
        class="px-4 py-2 rounded-full border text-sm font-serif transition"
        :class="selectedWord === e.word
          ? 'border-amber-500 bg-amber-50 text-amber-900'
          : 'border-stone-300 bg-white hover:border-stone-400'"
      >
        {{ e.word }}
      </button>
    </div>

    <!-- Level selector -->
    <div class="flex flex-wrap gap-2 mb-8 text-xs">
      <span class="text-stone-500 self-center mr-2">Reading level:</span>
      <button
        v-for="(label, lvl) in LEVEL_LABELS"
        :key="lvl"
        @click="selectedLevel = lvl as Level"
        class="px-3 py-1 rounded-full border font-medium transition"
        :class="selectedLevel === lvl
          ? 'bg-amber-100 border-amber-400 text-amber-900'
          : 'bg-white border-stone-300 text-stone-600 hover:border-stone-400'"
      >{{ label }}</button>
    </div>

    <!-- Entry display -->
    <article v-if="current" class="def-card p-8 space-y-6">
      <header class="border-b border-stone-200 pb-4">
        <h2 class="text-4xl font-serif">{{ current.word }}</h2>
        <p class="text-amber-700 mt-2 font-serif text-lg italic">
          {{ current.levels[selectedLevel].headline }}
        </p>
      </header>

      <div class="font-serif text-lg leading-relaxed text-stone-900">
        <LinkedDefinition :text="current.levels[selectedLevel].body" />
      </div>

      <section v-if="current.levels[selectedLevel].key_passages?.length" class="border-t border-stone-200 pt-4">
        <h3 class="text-xs uppercase tracking-wider text-stone-500 mb-2 font-sans">Key passages</h3>
        <ul class="text-sm text-stone-700 flex flex-wrap gap-2">
          <li v-for="p in current.levels[selectedLevel].key_passages" :key="p" class="bg-stone-100 px-2.5 py-1 rounded font-mono text-xs">{{ p }}</li>
        </ul>
      </section>

      <section v-if="current.levels[selectedLevel].conference_refs?.length" class="border-t border-stone-200 pt-4">
        <h3 class="text-xs uppercase tracking-wider text-stone-500 mb-2 font-sans">Reinforcement (General Conference / Restoration teaching)</h3>
        <ul class="text-sm text-stone-700 list-disc list-outside ml-5 space-y-1">
          <li v-for="r in current.levels[selectedLevel].conference_refs" :key="r">{{ r }}</li>
        </ul>
      </section>

      <section v-if="current.webster_1828_compare" class="border-t border-stone-200 pt-4 bg-stone-50/40 -mx-8 -mb-8 px-8 pb-8 rounded-b-lg">
        <h3 class="text-xs uppercase tracking-wider text-stone-500 mb-2 font-sans">Compare to Webster 1828</h3>
        <p class="text-sm text-stone-700 leading-relaxed">
          <LinkedDefinition :text="current.webster_1828_compare" />
        </p>
      </section>

      <section v-if="current.substrate_study" class="border-t border-stone-200 pt-4">
        <h3 class="text-xs uppercase tracking-wider text-stone-500 mb-2 font-sans">Substrate study that lensed this word</h3>
        <a
          :href="`https://github.com/cpuchip/scripture-study/blob/main/${current.substrate_study.replace(/^[./]+/, '')}`"
          target="_blank"
          rel="noopener"
          class="text-sm text-amber-700 hover:underline font-mono"
        >{{ current.substrate_study.replace(/^[./]+/, '') }} ↗</a>
      </section>
    </article>

    <section class="mt-12 def-card p-6 bg-stone-50/40">
      <h2 class="font-serif text-lg mb-3">What's coming</h2>
      <ul class="text-sm text-stone-700 space-y-2 list-disc list-outside ml-5">
        <li>Substrate-pipeline-generated entries for ~150-200 doctrinal words. Each entry researched against the gospel-library/ corpus + BYU Citation Index for GC reinforcement.</li>
        <li>Cross-reference to Webster 1828 entries (where the 1828 lens illuminates) and to our existing studies (where we've lensed the word ourselves).</li>
        <li>Decisions needed before generation: working name (Thummim / Stuffleberry / Restoration Lexicon / other?), grade-level voice calibration, generation budget, citation density. See proposal §V.</li>
      </ul>
    </section>
  </div>
</template>
