"""
Compose research/gospel/1828/01-webster-references-in-studies.md from raw-citations.jsonl.

Group by word, aggregate tags across all citations of that word, sample
a definition excerpt, list every study that lensed it with a relative link.

Provenance: 2026-05-20 autonomous overnight task.
"""
from __future__ import annotations
import json
from collections import defaultdict, Counter
from pathlib import Path

REPO = Path("C:/Users/cpuch/Documents/code/stuffleberry/scripture-study")
JSONL = REPO / "research/gospel/1828/.work/raw-citations.jsonl"
OUT = REPO / "research/gospel/1828/01-webster-references-in-studies.md"


def main():
    rows = [json.loads(l) for l in JSONL.read_text(encoding="utf-8").splitlines() if l.strip()]
    by_word: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        if r["word"]:
            by_word[r["word"]].append(r)

    # Aggregate per word
    word_records = []
    for word, citations in by_word.items():
        tag_count = Counter(r["tag"] for r in citations)
        # Dominant tag: differ > reinforce > neutral when tied
        if tag_count["differ"] > 0:
            tag = "differ"
        elif tag_count["reinforce"] > 0:
            tag = "reinforce"
        else:
            tag = "neutral"
        studies = sorted({r["study"] for r in citations})
        # First non-empty citation excerpt as sample
        sample = next((r["definition_excerpt"] for r in citations if r["definition_excerpt"]), "")
        word_records.append({
            "word": word,
            "n_citations": len(citations),
            "n_studies": len(studies),
            "tag": tag,
            "tag_breakdown": dict(tag_count),
            "studies": studies,
            "sample": sample,
        })
    # Sort: differ first (most interesting), then by citation count desc
    tag_order = {"differ": 0, "reinforce": 1, "neutral": 2}
    word_records.sort(key=lambda r: (tag_order[r["tag"]], -r["n_citations"], r["word"]))

    # Compose markdown
    lines = []
    lines.append("# Webster 1828 references in our studies")
    lines.append("")
    lines.append("**Source:** every `study/**/*.md` file (excluding `.scratch/`)")
    lines.append("**Method:** Python tokenization of citation windows around \"Webster 1828\" mentions; words extracted only from explicit markup (bold/italic/quotes/headings)")
    lines.append("**Date:** 2026-05-20")
    lines.append("**Provenance:** generated by `research/gospel/1828/.work/extract_webster_citations.py` and `compose_p1_table.py`")
    lines.append("")
    lines.append(f"**Counts:** {len(rows)} raw rows · {sum(1 for r in rows if r['word'])} attributed · {len(word_records)} unique words · {sum(r['n_citations'] for r in word_records)} confirmed citations across {len({s for r in word_records for s in r['studies']})} distinct study files")
    lines.append("")
    lines.append("**Tag legend:**")
    lines.append("- **differ** — the citation context names a difference between 1828 and modern usage (or recovers a sense modern English has lost). These are the highest-value highlight candidates.")
    lines.append("- **reinforce** — the citation context says 1828 matches or sharpens the Restoration sense. Confirms an existing reading rather than overturning one.")
    lines.append("- **neutral** — the citation defines a word but the context doesn't explicitly frame it as differ/reinforce.")
    lines.append("")
    lines.append("**Heuristic limitations to acknowledge:**")
    lines.append("- The differ/reinforce tag is keyword-based; final tier curation in `00-FINAL-highlight-candidates.md` revisits each manually.")
    lines.append("- Generic words (`why`, `from`, `both`, `through`, etc.) leak through when they appear in markup near a Webster citation. P5 synthesis filters them.")
    lines.append("- 62 of 373 citation rows had no extractable word; usually quoted-scripture-only blocks adjacent to a real citation. Counted but not tabulated below.")
    lines.append("")

    # The intelligence study case Michael mentioned
    intel_rows = [r for r in word_records if r["word"] == "intelligence"]
    if intel_rows:
        ir = intel_rows[0]
        lines.append("## Intelligence study — the case Michael flagged")
        lines.append("")
        lines.append(f"`intelligence` lensed in {ir['n_studies']} studies ({ir['n_citations']} citations), tag: **{ir['tag']}**")
        lines.append("")
        lines.append("Studies:")
        for s in ir["studies"]:
            lines.append(f"- [`{s}`](../../../{s})")
        lines.append("")
        lines.append(f"Sample citation excerpt: *{ir['sample'][:300]}*")
        lines.append("")
        lines.append("This is the case where 1828's *\"the intelligent, immaterial and immortal part of man\"* recovers a sense modern English loses — modern \"intelligence\" is cognitive ability; 1828 (and D&C 93) treat it as the substance of being itself. The matter-spectrum study (`truth.md`) makes this explicit.")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Full table
    lines.append("## All cited words")
    lines.append("")
    lines.append("Sorted: `differ` first (highest-signal candidates), then by citation count.")
    lines.append("")
    lines.append("| Word | Tag | Citations | Studies | Studies (sample) |")
    lines.append("|------|-----|-----------|---------|------------------|")
    for r in word_records:
        # Limit displayed studies to 3 for table compactness; full list in detail section
        sample_studies = ", ".join(f"[`{s.split('/')[-1].replace('.md','')}`]({'../' * 3}{s})" for s in r["studies"][:3])
        if len(r["studies"]) > 3:
            sample_studies += f" (+{len(r['studies']) - 3} more)"
        lines.append(f"| **{r['word']}** | {r['tag']} | {r['n_citations']} | {r['n_studies']} | {sample_studies} |")
    lines.append("")

    # Detail section — every word, every citation
    lines.append("## Detail — every citation")
    lines.append("")
    lines.append("Each entry: word · all studies that lensed it · sample citation line. Hover/click-target for the highlight tool's curation tier.")
    lines.append("")
    for r in word_records:
        lines.append(f"### `{r['word']}` — *{r['tag']}* ({r['n_citations']} citations across {r['n_studies']} studies)")
        lines.append("")
        if r["tag_breakdown"]:
            tb = ", ".join(f"{k}={v}" for k, v in sorted(r["tag_breakdown"].items()))
            lines.append(f"Tag breakdown: {tb}")
        lines.append("")
        lines.append("Studies:")
        for s in r["studies"]:
            lines.append(f"- [`{s}`](../../../{s})")
        lines.append("")
        if r["sample"]:
            lines.append(f"> {r['sample'][:400]}")
            lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
