"""
Phase 2 — derive a confirmed-from-studies highlight list from P1 raw data.

Tier logic:
- A: 3+ studies AND has at least one "differ" tag — repeatedly invoked AND
     framed as a meaning-shift recovery. High confidence for highlight.
- B: 2+ studies (any tag) — independently lensed twice. Verified.
- C: 1 study — interesting but speculative until cross-checked.

A manual REJECT list filters obvious noise that leaked through the
markup heuristic (generic words that happened to be quoted near a
citation but were not the dictionary lookup target).

Provenance: 2026-05-20 autonomous overnight task.
"""
from __future__ import annotations
import json
from collections import defaultdict, Counter
from pathlib import Path

REPO = Path("C:/Users/cpuch/Documents/code/stuffleberry/scripture-study")
JSONL = REPO / "research/gospel/1828/.work/raw-citations.jsonl"
OUT = REPO / "research/gospel/1828/02-confirmed-from-studies.md"

# Words to reject — generic English that leaked through extraction because
# they were quoted near a citation but were not the dictionary lookup target.
# Conservative — when in doubt, keep.
REJECT = {
    # Function words / generic
    "why", "how", "what", "when", "where", "who", "which",
    "both", "all", "any", "every", "some", "one", "two",
    "from", "into", "with", "through", "without", "across",
    "before", "after", "during", "until", "while", "since",
    "above", "below", "between", "among",
    "stops", "starts", "ends", "becomes", "become", "stays",
    # Quoted scripture-text artifacts (multi-word phrases that survived as single words)
    "saith", "thereof", "whereof",
    # Common verbs that show up in commentary but weren't lensed
    "use", "take", "make", "give", "set", "put", "see", "know",
    "find", "feel", "look", "say", "want", "need", "tell", "ask",
    # Personal pronouns / common nouns that aren't dictionary lookups
    "man", "men", "woman", "women", "people", "person",
    "day", "days", "night", "year", "years", "time",
    "way", "ways", "thing", "things",
    # Common adverbs / qualifiers
    "very", "just", "only", "still", "again", "even", "also",
    "more", "less", "most", "least", "much", "many", "few",
}


def main():
    rows = [json.loads(l) for l in JSONL.read_text(encoding="utf-8").splitlines() if l.strip()]
    by_word: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        if r["word"] and r["word"] not in REJECT:
            by_word[r["word"]].append(r)

    records = []
    for word, citations in by_word.items():
        studies = sorted({r["study"] for r in citations})
        tag_count = Counter(r["tag"] for r in citations)
        has_differ = tag_count["differ"] > 0
        has_reinforce = tag_count["reinforce"] > 0
        # Tier assignment
        if len(studies) >= 3 and has_differ:
            tier = "A"
        elif len(studies) >= 2:
            tier = "B"
        else:
            tier = "C"
        records.append({
            "word": word,
            "tier": tier,
            "n_studies": len(studies),
            "n_citations": len(citations),
            "has_differ": has_differ,
            "has_reinforce": has_reinforce,
            "studies": studies,
            "sample": next((r["definition_excerpt"] for r in citations if r["definition_excerpt"]), "")[:400],
        })
    # Sort: tier A first, then by study count, then alphabetical
    tier_order = {"A": 0, "B": 1, "C": 2}
    records.sort(key=lambda r: (tier_order[r["tier"]], -r["n_studies"], r["word"]))

    tier_a = [r for r in records if r["tier"] == "A"]
    tier_b = [r for r in records if r["tier"] == "B"]
    tier_c = [r for r in records if r["tier"] == "C"]

    lines = []
    lines.append("# Confirmed-from-studies highlight list")
    lines.append("")
    lines.append("**Source:** [`01-webster-references-in-studies.md`](01-webster-references-in-studies.md) — the table of every Webster 1828 citation across `study/**`.")
    lines.append("**Method:** group P1 citations by word, drop a small manual REJECT list of generic words that leaked through markup extraction, assign confidence tier.")
    lines.append("**Date:** 2026-05-20")
    lines.append("**Provenance:** generated by `research/gospel/1828/.work/compose_p2_confirmed.py`")
    lines.append("")
    lines.append("## Tier logic")
    lines.append("")
    lines.append("- **Tier A** — lensed in 3+ studies AND at least one citation context names a 1828-vs-modern *difference*. Repeatedly invoked AND framed as meaning-recovery. **These are the highest-confidence highlight targets for the MVP.**")
    lines.append("- **Tier B** — lensed in 2+ studies (any tag). Independently invoked at least twice; the word has earned its place in our study vocabulary.")
    lines.append("- **Tier C** — lensed in 1 study only. Interesting but worth a manual look before adding to highlight set.")
    lines.append("")
    lines.append(f"**Counts:** Tier A = {len(tier_a)} · Tier B = {len(tier_b)} · Tier C = {len(tier_c)} · Total = {len(records)}")
    lines.append("")

    for tier, recs, blurb in [
        ("A", tier_a, "High-confidence: lensed in 3+ studies AND framed as a 1828-vs-modern meaning shift."),
        ("B", tier_b, "Mid-confidence: lensed in 2+ studies. Solid candidates."),
        ("C", tier_c, "Speculative: lensed once. Useful as a candidate pool but worth manual review."),
    ]:
        lines.append(f"## Tier {tier} ({len(recs)} words)")
        lines.append("")
        lines.append(blurb)
        lines.append("")
        if not recs:
            lines.append("(none)")
            lines.append("")
            continue
        lines.append("| Word | Studies | Citations | Differ? | Reinforce? | First lensed in |")
        lines.append("|------|---------|-----------|---------|------------|------------------|")
        for r in recs:
            first = r["studies"][0]
            differ = "✓" if r["has_differ"] else ""
            reinforce = "✓" if r["has_reinforce"] else ""
            lines.append(f"| **{r['word']}** | {r['n_studies']} | {r['n_citations']} | {differ} | {reinforce} | [`{first}`](../../../{first}) |")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)}")
    print(f"Tier A: {len(tier_a)}, Tier B: {len(tier_b)}, Tier C: {len(tier_c)}")


if __name__ == "__main__":
    main()
