<#
.SYNOPSIS
  Substrate SQL regression suite — boots a hermetic scratch Postgres from the
  dev image, replays the migration corpus in HISTORICAL order, diffs the result
  against the live dev substrate, and runs every verify-*.sql + smoke/*.sql.

.DESCRIPTION
  One run produces a markdown triage report under .spec/scratch/. Phases:

    1. migration-order.txt — generated from git first-add dates. The
       schema_migrations backfill recorded all pre-ledger files at one
       timestamp, so historical order lives only in git. Intra-commit order
       falls back to lexical (batch sub-steps are named in order: 7a < 7a2 < 7b).
    2. Scratch boot — `docker run` of the dev image WITHOUT
       shared_preload_libraries (no bgworker -> no HTTP, no providers; hermetic)
       and WITHOUT .env secrets. init/ runs CREATE EXTENSION vector+age+
       pg_ai_stewards, which installs the bundled lib.rs chain.
    3. Replay — every migration file in historical order, each via
       `psql -v ON_ERROR_STOP=1 -f` (the same way they were applied live),
       recorded into the scratch ledger. Excluded: the generated
       pg_ai_stewards--*.sql bundle (already in via CREATE EXTENSION, not
       idempotent) and verify-*/test-* scripts (not migrations).
    4. Parity diff vs live — functions (md5 of pg_get_functiondef), table
       columns, views, triggers. Catches the l13-class regression: an old
       definition silently overwriting a newer one.
    5. Verify files — run each against the scratch, PASS/FAIL triage. Files
       that assume live data or a running bgworker are expected to FAIL on a
       hermetic scratch; the report is for triage, not a green/red gate (v1).

  WHY HISTORICAL ORDER: `stewards-cli migrate` applies lexically, but the live
  substrate was built chronologically. Files that redefine the same object
  (compose_messages spans ct2-*, k*, l1, l13) make lexical order WRONG on a
  fresh DB — ct2-* (2026-06) sorts before l13 (2026-05) and would be
  overwritten. This harness replays git order to test the substrate as it
  actually exists; the lexical-bootstrap gap is a separate finding tracked in
  the report.

.EXAMPLE
  pwsh projects/pg-ai-stewards/extension/scripts/run-verify-suite.ps1
  pwsh .../run-verify-suite.ps1 -KeepContainer   # leave scratch up to inspect
#>
param(
    [int]$Port = 55434,
    [string]$ContainerName = "pg-stewards-verify",
    [string]$Image = "pg-ai-stewards-dev:pg18",
    [string]$LiveContainer = "pg-ai-stewards-dev",
    [switch]$KeepContainer,
    [switch]$SkipVerifyFiles
)

$ErrorActionPreference = "Stop"
$ExtDir   = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$RepoRoot = (Resolve-Path (Join-Path $ExtDir "..\..\..")).Path
$ReportDir = Join-Path $RepoRoot "projects\pg-ai-stewards\.spec\scratch"
$Stamp = Get-Date -Format "yyyy-MM-dd-HHmm"
$ReportPath = Join-Path $ReportDir "verify-suite-report-$Stamp.md"
if (-not (Test-Path $ReportDir)) { New-Item -ItemType Directory -Force $ReportDir | Out-Null }

function Scratch-Psql { param([string[]]$PsqlArgs)
    docker exec $ContainerName psql -U stewards -d stewards @PsqlArgs 2>&1
}
function Live-Psql { param([string[]]$PsqlArgs)
    docker exec $LiveContainer psql -U stewards -d stewards @PsqlArgs 2>&1
}

# ---------------------------------------------------------------------------
# 1. Migration order from git history
# ---------------------------------------------------------------------------
Write-Host "[1/6] Generating migration order from git first-add dates..."
$gitOut = git -C $RepoRoot log --reverse --format="COMMIT %H" --diff-filter=A --name-only -- "projects/pg-ai-stewards/extension"
$order = [System.Collections.Generic.List[string]]::new()
$seen = @{}
foreach ($line in $gitOut) {
    if ($line -match '^projects/pg-ai-stewards/extension/([^/]+\.sql)$') {
        $name = $Matches[1]
        if (-not $seen.ContainsKey($name)) { $seen[$name] = $true; $order.Add($name) }
    }
}
# Disk files never added to git (or added after HEAD): append lexically, flagged.
$unGit = @()
Get-ChildItem -Path $ExtDir -Filter "*.sql" -File | Sort-Object Name | ForEach-Object {
    if (-not $seen.ContainsKey($_.Name)) { $order.Add($_.Name); $seen[$_.Name] = $true; $unGit += $_.Name }
}
# Drop names whose file no longer exists on disk.
$order = @($order | Where-Object { Test-Path (Join-Path $ExtDir $_) })

$manifest = Join-Path $ExtDir "migration-order.txt"
@(
    "# Historical apply order for extension/*.sql — generated by run-verify-suite.ps1 ($Stamp)."
    "# Source: git first-add order (intra-commit lexical). The schema_migrations"
    "# backfill lost pre-ledger ordering; this manifest is the recoverable truth."
    "# A fresh-DB bootstrap MUST use this order, not lexical (see compose_messages)."
) + $order | Set-Content -Path $manifest -Encoding utf8
Write-Host "      $($order.Count) files; $($unGit.Count) not in git history (appended last)."

# ---------------------------------------------------------------------------
# 2. Scratch container boot (hermetic: no preload, no secrets)
#
# init/ is deliberately NOT mounted: the image's bundled extension script may
# predate the 5d4 fresh-DB guard fix (an old RAISE EXCEPTION there makes
# CREATE EXTENSION fail on any virgin database — DR bug found 2026-06-09).
# We boot a plain cluster, shim the bundled script in-container (no-op once
# the image is rebuilt with the fixed file), then run init/00-extensions.sql
# ourselves.
# ---------------------------------------------------------------------------
Write-Host "[2/6] Booting scratch container $ContainerName (port $Port)..."
docker rm -f $ContainerName 2>$null | Out-Null
docker run -d --name $ContainerName `
    -e POSTGRES_USER=stewards -e POSTGRES_PASSWORD=stewards -e POSTGRES_DB=stewards `
    -p "${Port}:5432" `
    -v "${ExtDir}:/migrations:ro" `
    $Image | Out-Null

$ready = $false
for ($i = 0; $i -lt 45; $i++) {
    Start-Sleep -Seconds 2
    $null = docker exec $ContainerName psql -U stewards -d stewards -At -c "SELECT 1" 2>$null
    if ($LASTEXITCODE -eq 0) {
        # initdb runs a temp server first; confirm stability with a second probe.
        Start-Sleep -Seconds 3
        $null = docker exec $ContainerName psql -U stewards -d stewards -At -c "SELECT 1" 2>$null
        if ($LASTEXITCODE -eq 0) { $ready = $true; break }
    }
}
if (-not $ready) {
    docker logs --tail 50 $ContainerName
    docker rm -f $ContainerName 2>$null | Out-Null
    throw "Scratch container did not become ready (initdb failed)."
}

# 5d4 shim: the bundle inside the image may still carry the pre-fix RAISE
# EXCEPTION. Downgrade it to NOTICE (the following UPDATE no-ops on an empty
# work_items table). Idempotent: no match -> no change.
$null = docker exec $ContainerName sh -c "sed -i `"s/RAISE EXCEPTION '5d4 backfill/RAISE NOTICE '5d4 backfill/`" /usr/share/postgresql/*/extension/pg_ai_stewards--*.sql"

$out = docker exec $ContainerName psql -U stewards -d stewards -v ON_ERROR_STOP=1 -f /migrations/init/00-extensions.sql 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host ($out | Select-Object -Last 15)
    docker rm -f $ContainerName 2>$null | Out-Null
    throw "CREATE EXTENSION bootstrap failed on scratch (see output above)."
}
$ver = docker exec $ContainerName psql -U stewards -d stewards -At -c "SELECT stewards.version()" 2>&1
if ($LASTEXITCODE -ne 0) { throw "stewards.version() not callable after bootstrap: $ver" }
Write-Host "      Ready. Extension installed (version $ver)."

try {
    # -----------------------------------------------------------------------
    # 3. Ledger bootstrap + historical replay
    # -----------------------------------------------------------------------
    Write-Host "[3/6] Ledger bootstrap + replaying migrations in historical order..."
    $out = Scratch-Psql @("-q", "-v", "ON_ERROR_STOP=1", "-f", "/migrations/h-ledger-1-schema-migrations.sql")
    if ($LASTEXITCODE -ne 0) { throw "h-ledger-1 bootstrap failed: $out" }

    $genBundle = Get-ChildItem $ExtDir -Filter "pg_ai_stewards--*.sql" -File | Select-Object -First 1
    if ($genBundle) {
        $sha = (Get-FileHash $genBundle.FullName -Algorithm SHA256).Hash.ToLower()
        Scratch-Psql @("-q", "-c", "INSERT INTO stewards.schema_migrations (name, sha256, notes) VALUES ('$($genBundle.BaseName)', '$sha', 'pre-recorded by verify-suite: generated bundle, installed via CREATE EXTENSION') ON CONFLICT (name) DO NOTHING;") | Out-Null
    }

    $replayOk = [System.Collections.Generic.List[string]]::new()
    $replayFail = @()
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    foreach ($name in $order) {
        if ($name -like "pg_ai_stewards--*") { continue }
        if ($name -like "verify-*" -or $name -like "test-*") { continue }
        $out = Scratch-Psql @("-q", "-v", "ON_ERROR_STOP=1", "-f", "/migrations/$name")
        if ($LASTEXITCODE -eq 0) {
            $replayOk.Add($name)
            $sha = (Get-FileHash (Join-Path $ExtDir $name) -Algorithm SHA256).Hash.ToLower()
            $base = $name -replace '\.sql$', ''
            Scratch-Psql @("-q", "-c", "INSERT INTO stewards.schema_migrations (name, sha256, notes) VALUES ('$base', '$sha', 'replay') ON CONFLICT (name) DO NOTHING;") | Out-Null
        } else {
            $replayFail += [pscustomobject]@{
                Name  = $name
                Error = (($out | Select-Object -Last 6) -join "`n")
            }
            Write-Host "      FAIL  $name"
        }
    }
    $sw.Stop()
    Write-Host "      Replayed $($replayOk.Count) ok, $($replayFail.Count) failed, in $([int]$sw.Elapsed.TotalSeconds)s."

    # -----------------------------------------------------------------------
    # 4. Parity diff: scratch vs live
    # -----------------------------------------------------------------------
    Write-Host "[4/6] Diffing scratch vs live ($LiveContainer)..."
    $diffQueries = [ordered]@{
        functions = "SELECT p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')|' || md5(pg_get_functiondef(p.oid)) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'stewards' AND p.prokind IN ('f','p') ORDER BY 1"
        columns   = "SELECT c.table_name || '.' || c.column_name || '|' || c.data_type || '|' || coalesce(c.column_default, '-') FROM information_schema.columns c WHERE c.table_schema = 'stewards' ORDER BY 1"
        views     = "SELECT v.table_name || '|' || md5(v.view_definition) FROM information_schema.views v WHERE v.table_schema = 'stewards' ORDER BY 1"
        triggers  = "SELECT t.tgname || ' ON ' || c.relname || '|' || md5(pg_get_triggerdef(t.oid)) FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'stewards' AND NOT t.tgisinternal ORDER BY 1"
    }
    $parity = [ordered]@{}
    foreach ($kind in $diffQueries.Keys) {
        $q = $diffQueries[$kind]
        $scratchRows = @(Scratch-Psql @("-At", "-c", $q))
        if ($LASTEXITCODE -ne 0) { throw "parity query ($kind) failed on scratch: $scratchRows" }
        $liveRows = @(Live-Psql @("-At", "-c", $q))
        if ($LASTEXITCODE -ne 0) { throw "parity query ($kind) failed on live: $liveRows" }

        $sMap = @{}; foreach ($r in $scratchRows) { $p = $r -split '\|'; if ($p.Count -ge 2) { $sMap[$p[0]] = $p[-1] } }
        $lMap = @{}; foreach ($r in $liveRows)    { $p = $r -split '\|'; if ($p.Count -ge 2) { $lMap[$p[0]] = $p[-1] } }

        $missingInScratch = @($lMap.Keys | Where-Object { -not $sMap.ContainsKey($_) } | Sort-Object)
        $extraInScratch   = @($sMap.Keys | Where-Object { -not $lMap.ContainsKey($_) } | Sort-Object)
        $mismatch         = @($lMap.Keys | Where-Object { $sMap.ContainsKey($_) -and $sMap[$_] -ne $lMap[$_] } | Sort-Object)
        $parity[$kind] = [pscustomobject]@{
            Live = $lMap.Count; Scratch = $sMap.Count
            MissingInScratch = $missingInScratch; ExtraInScratch = $extraInScratch; Mismatch = $mismatch
        }
        Write-Host ("      {0}: live={1} scratch={2} missing={3} extra={4} mismatch={5}" -f $kind, $lMap.Count, $sMap.Count, $missingInScratch.Count, $extraInScratch.Count, $mismatch.Count)
    }

    # -----------------------------------------------------------------------
    # 5. Verify + smoke files against the scratch
    # -----------------------------------------------------------------------
    $verifyResults = @()
    if (-not $SkipVerifyFiles) {
        Write-Host "[5/6] Running verify-*.sql + smoke/*.sql against scratch..."
        $vFiles = @(Get-ChildItem $ExtDir -Filter "verify-*.sql" -File | Sort-Object Name | ForEach-Object { $_.Name })
        $vFiles += @(Get-ChildItem $ExtDir -Filter "test-*.sql" -File | Sort-Object Name | ForEach-Object { $_.Name })
        $smokeDir = Join-Path $ExtDir "smoke"
        if (Test-Path $smokeDir) {
            $vFiles += @(Get-ChildItem $smokeDir -Filter "*.sql" -File | Sort-Object Name | ForEach-Object { "smoke/$($_.Name)" })
        }
        foreach ($rel in $vFiles) {
            $out = Scratch-Psql @("-v", "ON_ERROR_STOP=1", "-f", "/migrations/$rel")
            $verifyResults += [pscustomobject]@{
                File = $rel
                Pass = ($LASTEXITCODE -eq 0)
                Tail = (($out | Select-Object -Last 8) -join "`n")
            }
        }
        $passN = @($verifyResults | Where-Object Pass).Count
        Write-Host "      $passN / $($verifyResults.Count) passed on hermetic scratch."
    } else {
        Write-Host "[5/6] Skipped (-SkipVerifyFiles)."
    }

    # -----------------------------------------------------------------------
    # 6. Report
    # -----------------------------------------------------------------------
    Write-Host "[6/6] Writing report -> $ReportPath"
    $r = [System.Collections.Generic.List[string]]::new()
    $r.Add("# Verify-suite report — $Stamp")
    $r.Add("")
    $r.Add("Scratch: ``$Image`` as ``$ContainerName`` (hermetic: no bgworker, no provider secrets). Live: ``$LiveContainer``.")
    $r.Add("Replay order: ``extension/migration-order.txt`` (git first-add; intra-commit lexical).")
    $r.Add("")
    $r.Add("## 1. Bootstrap replay")
    $r.Add("")
    $r.Add("| | count |")
    $r.Add("|---|---|")
    $r.Add("| replayed ok | $($replayOk.Count) |")
    $r.Add("| failed | $($replayFail.Count) |")
    $r.Add("| not in git (appended last) | $($unGit.Count) |")
    if ($replayFail.Count -gt 0) {
        $r.Add("")
        $r.Add("### Replay failures")
        foreach ($f in $replayFail) {
            $r.Add("")
            $r.Add("**$($f.Name)**")
            $r.Add('```')
            $r.Add($f.Error)
            $r.Add('```')
        }
    }
    $r.Add("")
    $r.Add("## 2. Parity vs live")
    $r.Add("")
    $r.Add("| object | live | scratch | missing in scratch | extra in scratch | def mismatch |")
    $r.Add("|---|---|---|---|---|---|")
    foreach ($kind in $parity.Keys) {
        $p = $parity[$kind]
        $r.Add("| $kind | $($p.Live) | $($p.Scratch) | $($p.MissingInScratch.Count) | $($p.ExtraInScratch.Count) | $($p.Mismatch.Count) |")
    }
    foreach ($kind in $parity.Keys) {
        $p = $parity[$kind]
        if ($p.MissingInScratch.Count + $p.ExtraInScratch.Count + $p.Mismatch.Count -gt 0) {
            $r.Add("")
            $r.Add("### $kind detail")
            if ($p.MissingInScratch.Count -gt 0) { $r.Add(""); $r.Add("Missing in scratch (live-only — never landed in repo files, or replay failure):"); $p.MissingInScratch | ForEach-Object { $r.Add("- ``$_``") } }
            if ($p.ExtraInScratch.Count -gt 0)   { $r.Add(""); $r.Add("Extra in scratch (repo-only — never applied live?):"); $p.ExtraInScratch | ForEach-Object { $r.Add("- ``$_``") } }
            if ($p.Mismatch.Count -gt 0)         { $r.Add(""); $r.Add("Definition mismatch (replay produced a different definition than live):"); $p.Mismatch | ForEach-Object { $r.Add("- ``$_``") } }
        }
    }
    if (-not $SkipVerifyFiles) {
        $r.Add("")
        $r.Add("## 3. Verify/smoke files (hermetic scratch)")
        $r.Add("")
        $r.Add("Failures here are NOT all regressions: files that assume live data, a running")
        $r.Add("bgworker, or provider HTTP will fail on a hermetic scratch by design. Triage column is the point.")
        $r.Add("")
        $r.Add("| file | result |")
        $r.Add("|---|---|")
        foreach ($v in $verifyResults) {
            $res = if ($v.Pass) { "PASS" } else { "FAIL" }
            $r.Add("| ``$($v.File)`` | $res |")
        }
        $fails = @($verifyResults | Where-Object { -not $_.Pass })
        if ($fails.Count -gt 0) {
            $r.Add("")
            $r.Add("### Failure tails")
            foreach ($v in $fails) {
                $r.Add("")
                $r.Add("**$($v.File)**")
                $r.Add('```')
                $r.Add($v.Tail)
                $r.Add('```')
            }
        }
    }
    $r | Set-Content -Path $ReportPath -Encoding utf8
    Write-Host ""
    Write-Host "Done. Report: $ReportPath"
}
finally {
    if ($KeepContainer) {
        Write-Host "Scratch container kept: $ContainerName (port $Port). Remove with: docker rm -f $ContainerName"
    } else {
        docker rm -f $ContainerName 2>$null | Out-Null
    }
}
